const {
  VULNERABILITY_SEVERITIES,
} = require("../constants/vulnerability.constants");

const { ASSET_CRITICALITIES } = require("../constants/asset.constants");

const { FINDING_PRIORITIES } = require("../constants/finding.constants");

// Matriz que combina severidad técnica y criticidad empresarial.
const PRIORITY_MATRIX = {
  [ASSET_CRITICALITIES.LOW]: {
    [VULNERABILITY_SEVERITIES.LOW]: FINDING_PRIORITIES.P4,
    [VULNERABILITY_SEVERITIES.MEDIUM]: FINDING_PRIORITIES.P4,
    [VULNERABILITY_SEVERITIES.HIGH]: FINDING_PRIORITIES.P3,
    [VULNERABILITY_SEVERITIES.CRITICAL]: FINDING_PRIORITIES.P2,
  },

  [ASSET_CRITICALITIES.MEDIUM]: {
    [VULNERABILITY_SEVERITIES.LOW]: FINDING_PRIORITIES.P4,
    [VULNERABILITY_SEVERITIES.MEDIUM]: FINDING_PRIORITIES.P3,
    [VULNERABILITY_SEVERITIES.HIGH]: FINDING_PRIORITIES.P2,
    [VULNERABILITY_SEVERITIES.CRITICAL]: FINDING_PRIORITIES.P2,
  },

  [ASSET_CRITICALITIES.HIGH]: {
    [VULNERABILITY_SEVERITIES.LOW]: FINDING_PRIORITIES.P3,
    [VULNERABILITY_SEVERITIES.MEDIUM]: FINDING_PRIORITIES.P2,
    [VULNERABILITY_SEVERITIES.HIGH]: FINDING_PRIORITIES.P2,
    [VULNERABILITY_SEVERITIES.CRITICAL]: FINDING_PRIORITIES.P1,
  },

  [ASSET_CRITICALITIES.CRITICAL]: {
    [VULNERABILITY_SEVERITIES.LOW]: FINDING_PRIORITIES.P2,
    [VULNERABILITY_SEVERITIES.MEDIUM]: FINDING_PRIORITIES.P2,
    [VULNERABILITY_SEVERITIES.HIGH]: FINDING_PRIORITIES.P1,
    [VULNERABILITY_SEVERITIES.CRITICAL]: FINDING_PRIORITIES.P1,
  },
};

// Devuelve la prioridad resultante de combinar ambos niveles de riesgo.
const calculatePriority = (severity, assetCriticality) => {
  const priority = PRIORITY_MATRIX[assetCriticality]?.[severity];

  if (!priority) {
    throw new Error("Invalid severity or asset criticality");
  }

  return priority;
};

module.exports = calculatePriority;
